version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    environment:
      PRODUCTS_SERVICE_HOST: $PRODUCTS_SERVICE_HOST
      PRODUCTS_SERVICE_PORT: $PRODUCTS_SERVICE_PORT
      RECOMMENDATIONS_SERVICE_HOST: $RECOMMENDATIONS_SERVICE_HOST
      RECOMMENDATIONS_SERVICE_PORT: $RECOMMENDATIONS_SERVICE_PORT
      VOTING_SERVICE_HOST: $VOTING_SERVICE_HOST
      VOTING_SERVICE_PORT: $VOTING_SERVICE_PORT

    ports:
      - "3000:3000"
    networks:
      - craftista-network

  recommendations:
    build:
      context: ./recommendation
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    networks:
      - craftista-network

  voting:
    build:
      context: ./voting
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - craftista-network

  products:
    build:
      context: ./catalogue
      dockerfile: Dockerfile
    ports:
      - "5900:5900"
    networks:
      - craftista-network

networks:
  craftista-network:
