version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    environment:
      CATALOGUE_URI: $CATALOGUE_URI
      RECOMMENDATIONS_URI: $RECOMMENDATIONS_URI
      VOTING_URI: $VOTING_URI

    ports:
      - "3000:3000"
    networks:
      - craftista-network

  recommendation:
    build:
      context: ./recommendation
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    networks:
      - craftista-network

  voting:
    build:
      context: ./voting
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - craftista-network

  catalogue:
    build:
      context: ./catalogue
      dockerfile: Dockerfile
    ports:
      - "5900:5900"
    networks:
      - craftista-network

networks:
  craftista-network:
